import SLSsyn as Ss
import control as co
import numpy as np
import matplotlib.pyplot as plt
import cvxpy as cvx


Ts = 0.008


def plant(kind='v1', tau_R1=0.0437, ke=10e3, br=10, kr=500, mr=0.05):
    # constant transfer function
    z = co.tf([1, 0], [1], Ts)
    s = co.tf([1, 0], [1])
    zero = co.tf([0], [1], Ts)
    one = co.tf([1], [1], Ts)

    R1 = 1 / (1 + tau_R1 * s)
    if kind == 'v1':
        """
        This model is generated by running Jan09_model_derivation.py
        outputs = [z1, x, y1, y2]
        inputs = [fd, xe, n, u1]
        """
        P = Ss.tf_blocks([
            [0, z ** (-2) * co.c2d(ke*(br*s + kr)/(br*s + ke + kr + mr*s**2), Ts), 0, z ** (-4) * co.c2d(-R1*(br*ke*s + br*mr*s**3 + ke*kr + kr*mr*s**2)/(br*s + ke + kr + mr*s**2), Ts)],
            [0, 0, 0, z ** (-2) * co.c2d(R1, Ts)],
            [1,                                                    0, 0,                                                                                     0],
            [0, z ** (-2) * co.c2d(ke*(br*s + kr)/(br*s + ke + kr + mr*s**2), Ts), 1, z ** (-4) * co.c2d(-R1*(br*ke*s + br*mr*s**3 + ke*kr + kr*mr*s**2)/(br*s + ke + kr + mr*s**2), Ts)]
        ])
    return P


if __name__ == '__main__':
    Pz_design = plant()
    # step_responses(P, 0.5)  # preview

    design_dict = {
        'ny': 2,
        'nu': 1,
        'Ntaps': 800,
        'Nsteps': 1000,
        'freqs': np.linspace(1e-2, np.pi / Ts, 1000),
        'resp_delay': 2,  # number of delayed time step

        # DC gain
        'dc-gain': [
            [(0, 0), 1],  # (fm, fd)
            [(0, 1), 0],  # (fm, xe)
        ],

        'freq-constraints': [
            [(0, 2), lambda omegas: np.ones_like(omegas)],
            [(1, 1), lambda omegas: np.ones_like(omegas)],
        ]
    }
    if input("Design controller?") == 'y':
        K_Qparam, data = Ss.Qsyn.Q_synthesis(Pz_design, design_dict)

    import IPython
    if IPython.get_ipython() is None:
        IPython.embed()
