# python 3. See associate org-node at 'system design notes' for more
# details. See Mujin, page 10.
import sympy as sym
import control as co
import SLSsyn as Ss


class PlantV1:
    @staticmethod
    def plant(tau_R1=0.0437, ke=10e3, br=10, kr=500, mr=0.05, Ts=0.008):
        """
        This model is generated by running Jan09_model_derivation.py
        outputs = [z1, x, y1, y2]
        inputs = [fd, xe, n, u1]
        """
        # constant transfer function
        z = co.tf([1, 0], [1], Ts)
        s = co.tf([1, 0], [1])

        R1 = 1 / (1 + tau_R1 * s)
        P = Ss.tf_blocks([
            [0, z ** (-2) * co.c2d(ke*(br*s + kr)/(br*s + ke + kr + mr*s**2), Ts), 0, z ** (-4) * co.c2d(-R1*(br*ke*s + br*mr*s**3 + ke*kr + kr*mr*s**2)/(br*s + ke + kr + mr*s**2), Ts)],
            [0, 0, 0, z ** (-2) * co.c2d(R1, Ts)],
            [1,                                                    0, 0,                                                                                     0],
            [0, z ** (-2) * co.c2d(ke*(br*s + kr)/(br*s + ke + kr + mr*s**2), Ts), 1, z ** (-4) * co.c2d(-R1*(br*ke*s + br*mr*s**3 + ke*kr + kr*mr*s**2)/(br*s + ke + kr + mr*s**2), Ts)]
        ])
        return P


    @staticmethod
    def derive():
        # dynamic symbols
        x, v, c, xe, ke, xr, vr = sym.symbols('x, v, c, xe, ke, xr, vr')
        # tool position, velocity and command
        # environment position, stiffness
        # robot position and velocity
        kr, br, mr, s = sym.symbols('kr, br, mr, s')  # tool stiffness, damping, mass and Laplace' s
        fm, fd, n = sym.symbols('fm fd n')  # measured force, desired force, noise
        f, R1 = sym.symbols('f R1')  # acting force, p2p transfer function
        Ts = sym.symbols('Ts') # sampling time

        # annotated symbols
        y1, y2, z1, z2, z3, u1, w1, w2, w3 = sym.symbols('y1, y2, z1, z2, z3, u1, w1, w2, w3')

        eqs = []
        eqs.extend([
            # robot dynamics
            xr - R1 * c * sym.exp(- 2 * Ts),
            vr - s * xr,
            v - s * x,
            fm - (kr * (x - xr) + br * (v - vr)) * sym.exp(- 2 * Ts),
            - (kr * (x - xr) + br * (v - vr)) + f - mr * v * s,

            # loop
            ke * (x - xe) + f,

            # input/output categorization
            fd - y1,
            y2 - (fm + n),
            c - u1,
            fd - w1,
            xe - w2,
            n - w3,
            fm - z1,
        ]
        )

        symdyn = [vr, xr, v, x, fm, f, c, fd, xe, n]
        symannot_out = [z1, xr, y1, y2]
        symannot_in = [w1, w2, w3, u1]

        sym2solve = symdyn + symannot_out
        res_ = sym.solve(eqs, sym2solve)
        # form overall tranfer matrix
        P = []
        for sym_out in symannot_out:
            t_ = sym.expand(res_[sym_out])
            terms = sym.collect(t_, symannot_in, evaluate=False)
            P.append([])
            for sym_in in symannot_in:
                if sym_in in terms:
                    P[-1].append(terms[sym_in].simplify())
                else:
                    P[-1].append(0)
                assert 1 not in terms, "there should not be any constant"
        P = sym.Matrix(P)
        P
