function P = Sep26_SISO_model(Larm, TR, TS, tauR1, tauR2, tauS, tauH, kH, bH, deltaH)
% Return a linear model of the admittance control robot. 

% The model has the following form:

% [d ] = [P11 P12] [fH]
% [mm]   [P21 P22] [qu]

% d:  position of the end-effector,
% mm: effective torque measured,
% fH: force exerted by human,
% qu: control generated by the admittance controller,

% default if no parameter is passed in
if nargin == 0
    Larm = 0.4;
    TR = 0.0437; % See org-note: Closed-loop characteristics of the Denso VS-060
    TS = 1 / (2 * pi * 73);  % filter at Nyquist freq
    tauR1 = 0.036;
    tauR2 = 0.03;
    tauS = 0.0;  % sensor
    tauH = 0;
    kH = 80;
    bH = 10;
    deltaH = 1;
end

% blocks
s = tf('s');
R1 = 1 / (TR * s + 1);
R1.InputDelay = tauR1;

R2 = - 0.5 * s^2 * 1e6 / (s^2 + 2e3 * s + 1e6) / (TR * s + 1); 
R2.InputDelay = tauR2;

Se = 1 / (TS * s + 1);
Se.InputDelay = tauS;

P11 = 0;
P12 = R1 * Larm;

P21 = Se * Larm;
P22 = (R2 - R1 * Larm * deltaH * (kH + s * bH)) * Se * Larm;

P = [P11 P12; P21 P22];

end